---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: wiping test config
    ios_config:
      lines:
        - default interface {{item.key}}
      provider: "{{ cli }}"
      match: none
    with_dict: "{{ interfaces }}"