---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Configure OSPF on interface
    ios_config:
      lines:
        - ip address {{item.value.ip}} {{item.value.netmask}}
        - ip ospf 1 area 0
        - ip ospf network point-to-point
        - no shutdown
      provider: "{{ cli }}"
      parents: interface {{item.key}}
    with_dict: "{{ interfaces }}"

