---
    
- name: configure spines
  hosts: spines
  connection: network_cli
  gather_facts: no

  roles: 
    - nxos
    # - spine

# - name: configure leaves
  # hosts: leaves
  # connection: network_cli
  # gather_facts: no

  # roles: 
    # - nxos
    # - leaf