---
- name: check Features
  hosts: nxos
  connection: network_cli
  gather_facts: no

  tasks:
  - name: wipe nxos devices
    nxos_command:
      commands:
        - rollback running-config checkpoint BLANK
