---

- name: configure OSPF
  hosts: nxos
  connection: local
  gather_facts: no

   
  tasks:
    - name: configure ospf domain 1
      nxos_ospf:
        state: present
        ospf: 1
        provider: "{{ nxos_provider }}"

    - name: configure ospf interface
      nxos_interface_ospf:
        area: 0
        provider: "{{ nxos_provider }}"
        interface: "{{ item.key }}"
        ospf: 1
        state: present
      with_dict: "{{ interfaces }}"

       