---
- name: check Features
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: wipe nxos devices
    nxos_command:
      commands:
        - rollback running-config checkpoint BLANK
    provider: "{{ nxos_provider }}"
    timeout: 60
  
