---

- name: configure EVPN
  hosts: nxos
  connection: local
  gather_facts: no

   
  tasks:
    - nxos_evpn_global:
        nv_overlay_evpn: true
            
    - nxos_vxlan_vtep:
        interface: nve1
        description: default
        host_reachability: default
        source_interface: Loopback1
        source_interface_hold_down_time: 30
        shutdown: default
        
    - nxos_vxlan_vtep_vni:
        interface: nve1
        vni: 6000
        ingress_replication: default
        
    - name: vni configuration
      nxos_evpn_vni:
        vni: 6000
        route_distinguisher: "60:10"
        route_target_import:
          - "5000:10"
          - "4100:100"
        route_target_export: auto
        route_target_both: default
        
    - name: VLAN-VNI mapping
      nxos_vlan:
        vlan_id: 50
        mapped_vni: 50000
        transport: nxapi
        
    - name: configure evpn address-family
      nxos_bgp_af:
        asn: 65535
        afi: l2vpn
        safi: evpn
        advertise_l2vpn_evpn: true
        provider: "{{ nxos_provider }}"
        
    - nxos_bgp_neighbor:
        asn: 65535
        neighbor: 3.3.3.3
        remote_as: 30
        update_source: Loopback1
        state: present

    - name: configure RR client
      nxos_bgp_neighbor_af:
        asn: 65535
        neighbor: '3.3.3.3'
        afi: l2vpn
        safi: evpn
        route_reflector_client: true
        
        

       