---
 #check features enabled
- name: enable leaf specific features
  nxos_feature:
    state: enabled
    feature: "{{ item }}"
    provider: "{{ nxos_provider }}"
  with_list: "{{ features }}"
  
- name: set nv overlay to evpn
  nxos_evpn_global:
        nv_overlay_evpn: true
        
- name: configure VTEP
  nxos_vxlan_vtep:
        interface: nve1
        description: default
        host_reachability: yes
        source_interface: Loopback1
        source_interface_hold_down_time: 30
        shutdown: no
  
- name: map VLANs to VNIs
  nxos_vlan:
    vlan_id: "{{ item.value.vlan }}"
    mapped_vni: "{{ item.value.vni }}"
    name: "{{ item.key }}"
  with_dict: "{{ vni_segments }}"
    
- name: vni evpn configuration
  nxos_evpn_vni:
    vni: "{{ item.value.vni }}"
    route_distinguisher: auto
    route_target_both: auto
  with_dict: "{{ vni_segments }}"
    
- name: map VNI to NVE
  nxos_vxlan_vtep_vni:
    interface: nve1
    vni: "{{ item.value.vni }}"
    ingress_replication: bgp
  with_dict: "{{ vni_segments }}"
