---
 #check features enabled
- name: enable leaf specific features
  nxos_feature:
    state: enabled
    feature: "{{ item }}"
    provider: "{{ nxos_provider }}"
  with_list: "{{ features }}"
  
- name: set nv overlay to evpn
  nxos_evpn_global:
        nv_overlay_evpn: true
        
- name: configure VTEP
  nxos_vxlan_vtep:
        interface: nve1
        description: default
        host_reachability: yes
        source_interface: Loopback1
        source_interface_hold_down_time: 30
        shutdown: no
        
- name: vni configuration
  nxos_evpn_vni:
    vni: 5000
    route_distinguisher: auto
    route_target_import:
      - auto
    route_target_export: auto
    route_target_both: default
    
- name: VLAN-VNI mapping
  nxos_vlan:
    vlan_id: 50
    mapped_vni: 5000
