---

- name: Validate fabric data model
  hosts: nxos
  connection: network_cli
  gather_facts: no

  tasks:
  
  - name: include vars
    include_vars:
      dir: fabric
      extensions:
        - yml
             
  # - name: build local loopback list
    # set_fact:
      # loop_interfaces: "{{ loop_interfaces | default([]) | combine (item) }}"
    # loop: "{{ loopbacks | json_query(jquery) }}"
    # vars:
      # jquery: '*.{{inventory_hostname}}'
      
  # - name: debug loopback_list
    # debug: 
      # msg: 
        # - "key: {{ item.key }}"
        # - "value: {{ item.value }}"
      
    # with_dict: "{{ loop_interfaces }}"
    # when: loop_interfaces is defined
    # loop_control:
      # label: "{{ item.key }}"
    
  - name: build leaf loopback list
    debug:
      msg: "{{ item | ipaddr('address') }}"
    loop: "{{ loopbacks | json_query('leaf.*.Loopback0') }}"
