---

- name: generate node values
  hosts: nxos
  connection: network_cli
  gather_facts: no
  
  tasks:
  
  - name: include evpn-fabric.yml
    include_vars:
      file: fabric/evpn-fabric.yml

  - name: include vni-segments.yml
    include_vars:
      file: fabric/vni-segments.yml
      
  - name: delete any existing files
    file: 
      path: "{{ item }}" 
      state: absent
    with_fileglob: "fabric/hosts-generated/{{inventory_hostname}}-model.yml"
      
  - name: create per-node model
    template: 
      src: fabric/per-node.j2 
      dest: "04-Deploy/fabric/hosts-generated/{{inventory_hostname}}-model.yml"
      trim_blocks: yes
      
  - name: include generated values
    include_vars:
      file: "fabric/hosts-generated/{{inventory_hostname}}-model.yml"
        
- name: configure nxos
  hosts: nxos
  connection: network_cli
  gather_facts: no

  roles: 
    - nxos

  
- name: configure spines
  hosts: spines
  connection: network_cli
  gather_facts: no

  roles: 
    - spine

- name: configure leaves
  hosts: leaves
  connection: network_cli
  gather_facts: no

  roles: 
    - leaf
    
- name: validate deployment
  hosts: nxos
  connection: network_cli
  gather_facts: no
  serial: 3
  
  tasks:
    - name: include validate-fabric.yml
      include: validate-fabric.yml