---
- name: prepare models
  hosts: nxos
  connection: network_cli
  gather_facts: no
  
  tasks:
  
    - name: include evpn-fabric.yml
      include_vars:
        file: fabric/evpn-fabric.yml
    
    - name: include vni-segments.yml
      include_vars:
        file: fabric/vni-segments.yml
        
    - name: delete any existing model
      file: 
        path: "{{ item }}" 
        state: absent
      with_fileglob: "fabric/hosts-generated/model/{{inventory_hostname}}-model.yml"
    
    - name: create per-node model
      template: 
        src: fabric/per-node.j2 
        dest: "04-Deploy/fabric/hosts-generated/model/{{inventory_hostname}}-model.yml"
        trim_blocks: yes
        
    - name: include generated information
      include_vars:
        file: "fabric/hosts-generated/model/{{inventory_hostname}}-model.yml"
    

      
- name: generate spine config
  hosts: spines
  connection: network_cli
  gather_facts: no

  tasks:
    - name: delete any existing config
      file: 
        path: "{{ item }}" 
        state: absent
      with_fileglob: "fabric/hosts-generated/config/{{inventory_hostname}}-config.txt"
      
    - name: create spine per-node config
      template: 
        src: fabric/spine-config.j2 
        dest: "04-Deploy/fabric/hosts-generated/config/{{inventory_hostname}}-config.txt"
        trim_blocks: yes
        


- name: generate leaf config
  hosts: leaves
  connection: network_cli
  gather_facts: no

  tasks: 
    - name: delete any existing config
      file: 
        path: "{{ item }}" 
        state: absent
      with_fileglob: "fabric/hosts-generated/config/{{inventory_hostname}}-config.txt"
        
    - name: create leaf per-node config
      template: 
        src: fabric/leaf-config.j2 
        dest: "04-Deploy/fabric/hosts-generated/config/{{inventory_hostname}}-config.txt"
        trim_blocks: yes
        
# - name: replace config
  # hosts: nxos
  # connection: network_cli
  # gather_facts: no
  
  # tasks:
  
    # - name: replace config
      # nxos_config:
        # replace_src: "04-Deploy/fabric/hosts-generated/config/{{inventory_hostname}}-config.txt"
        # replace: config
      # register: output
      
      
    # - debug:
        # msg: "{{ output }}"