---
l3_interfaces:
   Ethernet1/1:
    ip: 10.31.13.1/24
   
   Ethernet1/2:
    ip: 10.31.14.1/24
   
   Ethernet1/3:
    ip: 10.31.15.1/24
    
   Ethernet1/4:
    ip: 10.31.16.1/24
   
   Loopback0:
    ip: 1.1.1.1/32
