---
interfaces:
   Ethernet1/1:
    ip: 10.31.23.2
    mask: 24
   
   Ethernet1/2:
    ip: 10.31.24.2
    mask: 24
   
   Loopback0:
    ip: 2.2.2.2
    mask: 32
    loopback: True
   
    