---
l3_interfaces:
   Ethernet1/1:
    ip: 10.31.14.4
    mask: 24
   
   Ethernet1/2:
    ip: 10.31.24.4
    mask: 24
   
   Loopback0:
    ip: 4.4.4.4
    mask: 32
    loopback: True

   Loopback1:
    ip: 10.99.99.4
    mask: 32
    
l2_interfaces:
  Ethernet1/5:
    vlan: 101