features:
  - hsrp
  - interface-vlan
  - vpc
  - lacp
  - nv overlay
  - vn-segment-vlan-based
  
vni_segments:
  test1:
    vlan: 50
    vni: 5000
  test2:
    vlan: 60
    vni: 6000
  web:
    vlan: 100
    vni: 10000
    subnet: 10.0.0.1/24
  app:
    vlan: 101
    vni: 10100
    subnet: 11.0.0.1/24
  db:
    vlan: 102
    vni: 10200
    subnet: 12.0.0.1/24
  prod:
    vlan: 103
    vni: 10300
  octopus:
    vlan: 104
    vni: 10400
    